name: CI

on:
   workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
     - name: checkout-code
       uses: actions/checkout@v7

     - name: docker login
     
       uses: docker/login-action@v4
       with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
     - name: Build and push Docker image
       uses: docker/build-push-action@v7
       with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devobard-fe-master:latest

